package com.skj.perfect;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wheel.perfect.api.downapi.DownApkInfo;

import com.skj.perfect.DownApkInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downApkInfoDaoConfig;

    private final DownApkInfoDao downApkInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downApkInfoDaoConfig = daoConfigMap.get(DownApkInfoDao.class).clone();
        downApkInfoDaoConfig.initIdentityScope(type);

        downApkInfoDao = new DownApkInfoDao(downApkInfoDaoConfig, this);

        registerDao(DownApkInfo.class, downApkInfoDao);
    }
    
    public void clear() {
        downApkInfoDaoConfig.clearIdentityScope();
    }

    public DownApkInfoDao getDownApkInfoDao() {
        return downApkInfoDao;
    }

}
